#!/usr/bin/env node
const SteamAPI = require('steamapi');
const fs = require('fs');
const steam = new SteamAPI('ADD32972D02615E2F242478B9219C94D');
// var program = require('commander');

// program
//  .arguments('-k, --key <key>', 'The key generated by Steam')
//  .option('-u, --username <username>', 'The Steam user')
//  .action(function() {
//    console.log('user: %s pass: %s file: %s',
//        program.key, program.username);
//  })
//  .parse(process.argv);



steam.resolve('https://steamcommunity.com/id/ppuspfc').then(id => {
    console.log("Id do usuário Steam: " + id);
    steam.getUserOwnedGames(id).then(games => {
        let json = JSON.stringify(games);
        fs.writeFile('steamGames.json', json, 'utf8');
    });
});



